import Foundation
import Testing
@testable import Nootch

@Suite struct VibeSyncUpstreamParityTests {
    // Expected values are generated by the official JS parsers, independently
    // of the Swift implementation. Provenance and generator live with fixtures.
    @Test(arguments: ["amp", "dsh", "cline", "kiro", "cursor"])
    func officialGoldenFixtures(source: String) async throws {
        let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().appendingPathComponent("Fixtures/remaining-parsers")
        let expected = try #require(VibeParserSupport.json(root.appendingPathComponent("expected.json").path) as? [String: [String: Any]])
        let parser: any VibeLogParser
        switch source {
        case "amp": parser = VibeSyncAmpParser(threadsDir: root.appendingPathComponent("amp").path)
        case "dsh": parser = VibeSyncDshParser(sessionsDir: root.appendingPathComponent("dsh").path)
        case "cline": parser = VibeSyncClineParser(roots: [root.appendingPathComponent("cline").path], sessionDirs: [])
        case "kiro": parser = VibeSyncKiroParser(environment: ["KIRO_CLI_SESSIONS_DIR": root.appendingPathComponent("kiro").path], home: root.path)
        default:
            let data = try Data(contentsOf: root.appendingPathComponent("cursor.csv"))
            parser = VibeSyncCursorParser(dbPath: root.appendingPathComponent("cursor.vscdb").path, loader: { request in
                (data, HTTPURLResponse(url: request.url!, statusCode: 200, httpVersion: nil, headerFields: nil)!)
            })
        }
        let result = try await parser.parse()
        let buckets = VibeAggregation.aggregateToBuckets(result.entries, hostname: "test")
        let sessions = VibeAggregation.extractSessions(result.events)
        func normalized<T: Encodable>(_ value: T) throws -> [[String: Any]] {
            var objects = try #require(JSONSerialization.jsonObject(with: JSONEncoder().encode(value)) as? [[String: Any]])
            for i in objects.indices where objects[i]["hostname"] as? String != "cursor-cloud" { objects[i].removeValue(forKey: "hostname") }
            return objects
        }
        let actual: [String: Any] = ["buckets": try normalized(buckets), "sessions": try normalized(sessions), "skipped": result.skipped]
        let observed = try JSONSerialization.data(withJSONObject: actual, options: [.sortedKeys])
        let golden = try JSONSerialization.data(withJSONObject: #require(expected[source]), options: [.sortedKeys])
        #expect(String(decoding: observed, as: UTF8.self) == String(decoding: golden, as: UTF8.self))
    }
}
